apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-app-deployment
spec:
  selector:
    matchLabels:
      app: testing-app
  template:
    metadata:
      annotations:  
        dapr.io/app-id: testing-app
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
      labels:
        app: testing-app
    spec:
      containers:
      - name: agenda-service
        image: ko://github.com/salaboy/dapr-operator-integration-testing-app
        imagePullPolicy: Always
        env:
        - name: STATESTORE_NAME
          value: statestore
        livenessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: testing-app-service
spec:
  selector:
    app: testing-app
  ports:
  - port: 80
    targetPort: 8080
